import test from 'node:test'
import assert from 'node:assert/strict'
import {assignContract,editContract} from '../server/admin-contracts.js'
import {emptyDb,entry,balance,accrue,canWithdraw} from '../server/engine.js'
import {DAY} from '../src/rules.js'
const start=new Date('2026-09-01T15:00:00Z')
function fixture(){const db=emptyDb();db.rules.confirmed=true;const u={id:'u',name:'User',username:'user',email:'u@test.local',passwordHash:'',role:'ASSOCIATE' as const,status:'ACTIVE' as const,sponsorId:null,inviteCode:'user'};db.users.push(u,{...u,id:'admin',role:'ADMIN_MASTER'});entry(db,'u','deposit',10000,'fund','Test');return db}
const create={planId:'C-1',amount:25,source:'deposit',reason:'Atendimento solicitado',requestId:'request-admin-0001'}
test('administrador inclui plano, concessão é idempotente e participante não tem acesso',()=>{const db=fixture();assert.throws(()=>assignContract(db,'u','u',create,start),/restrito/);const before=balance(db,'u','deposit');const c=assignContract(db,'admin','u',{...create,source:'grant'},start)!;assert.equal(balance(db,'u','deposit'),before);assert.equal(assignContract(db,'admin','u',{...create,source:'grant'},start)!.id,c.id);assert.equal(db.contracts.length,1);assert.throws(()=>assignContract(db,'admin','u',create,start),/utilizado/);assert.equal(c.balancePrincipal,2500)})
test('edição mantém dias pagos, ajusta capital e não reescreve ganhos anteriores',()=>{const db=fixture(),c=assignContract(db,'admin','u',create,start)!;const patch={action:'edit',planId:'C-1',amount:40,rate:2,days:3,returnPrincipal:true,reason:'Correção acordada',revision:0};editContract(db,'admin','u',c.id,patch,new Date(+start+DAY));assert.equal(c.paidDays,1);assert.equal(balance(db,'u','locked'),200);assert.equal(balance(db,'u','deposit'),6000);assert.throws(()=>editContract(db,'admin','u',c.id,patch,new Date(+start+DAY)),/alterada/);accrue(db,new Date(+start+3*DAY));assert.equal(balance(db,'u','earnings'),4360);assert.equal(balance(db,'u','locked'),0);assert.equal(balance(db,'u','deposit'),6000);assert.equal(c.status,'CLOSED')})
test('redução devolve saldo restrito; encerramento libera o capital como saldo sacável',()=>{const db=fixture(),c=assignContract(db,'admin','u',{...create,amount:40},start)!;editContract(db,'admin','u',c.id,{action:'edit',planId:'C-1',amount:25,rate:6,days:30,returnPrincipal:true,reason:'Reduzir capital',revision:0},start);assert.equal(balance(db,'u','deposit'),7500);editContract(db,'admin','u',c.id,{action:'close',refund:true,revision:1,reason:'Devolver capital'},start);assert.equal(balance(db,'u','deposit'),7500);assert.equal(balance(db,'u','earnings'),2500);assert.equal(canWithdraw(db,'u',start),true);assert.throws(()=>editContract(db,'admin','u',c.id,{action:'close',refund:true,revision:2,reason:'Repetir encerramento'},start),/encerrada/)})
test('conversão em cofre e encerramento sem devolução mantêm contabilidade',()=>{const db=fixture(),c=assignContract(db,'admin','u',create,start)!;editContract(db,'admin','u',c.id,{action:'edit',planId:'CREDCOFRE',amount:25,rate:2,days:0,returnPrincipal:true,reason:'Transferir para cofre',revision:0},start);assert.equal(balance(db,'u','vault'),2500);editContract(db,'admin','u',c.id,{action:'close',refund:false,revision:1,reason:'Encerramento sem devolução'},new Date(+start+DAY));assert.equal(balance(db,'u','vault'),0);assert.equal(balance(db,'u','deposit'),7500);assert.equal(balance(db,'u','earnings'),0)})
