import test from 'node:test'
import assert from 'node:assert/strict'
import {emptyDb,entry,balance,subscribe,accrue,redeem} from '../server/engine.js'
import {savePlan,catalog} from '../server/catalog.js'
import {DAY,validatePlanLimits} from '../src/rules.js'
const start=new Date('2026-09-01T15:00:00Z')
const plan={id:'CUSTOM',name:'Plano personalizado',family:'cycle',days:2,min:2500,max:10000,bps:100,active:true,returnPrincipal:true,maxActive:1}
function fixture(){const db=emptyDb();db.rules.confirmed=true;db.users.push({id:'a',name:'Ana',username:'ana',email:'a@test.local',passwordHash:'',role:'ASSOCIATE',status:'ACTIVE',sponsorId:null,inviteCode:'ana'});entry(db,'a','deposit',100000,'fund','Teste');return db}
test('catálogo valida dados e códigos sem mutação em falhas',()=>{const db=fixture();assert.equal(catalog(db).length,9);savePlan(db,'admin',plan);for(const input of [{...plan},{...plan,id:'BAD',min:0},{...plan,id:'BAD',days:0},{...plan,id:'BAD',maxActive:0}]){const before=structuredClone(db);assert.throws(()=>savePlan(db,'admin',input));assert.deepEqual(db,before)}assert.throws(()=>savePlan(db,'admin',{id:'OTHER'},'CUSTOM'));validatePlanLimits(db.rules.activePlanLimits,catalog(db));savePlan(db,'admin',{active:false},'NEX-N1');assert.equal(catalog(db).find(p=>p.id==='NEX-N1')?.active,false)})
test('plano novo respeita limite, inativação e condições capturadas na compra',()=>{const db=fixture();savePlan(db,'admin',plan);const c=subscribe(db,'a','CUSTOM',2500,'deposit',start);assert.throws(()=>subscribe(db,'a','CUSTOM',2500,'deposit',start),/Limite/);savePlan(db,'admin',{name:'Novo nome',bps:900,days:10,returnPrincipal:false,active:false},'CUSTOM');const before=structuredClone(db);assert.throws(()=>subscribe(db,'a','CUSTOM',2500,'deposit',start));assert.deepEqual(db,before);accrue(db,new Date(+start+3*DAY));assert.equal(c.planName,plan.name);assert.equal(c.paidDays,2);assert.equal(balance(db,'a','earnings'),50);assert.equal(balance(db,'a','deposit'),100000)})
test('plano cadastrado paga comissão ao patrocinador elegível uma única vez',()=>{const db=fixture();subscribe(db,'a','C-1',2500,'deposit',start);db.users.push({...db.users[0],id:'b',username:'b',inviteCode:'b',sponsorId:'a'});entry(db,'b','deposit',5000,'fund-b','Teste');savePlan(db,'admin',plan);const c=subscribe(db,'b','CUSTOM',2500,'deposit',start,'custom-request-001');assert.equal(balance(db,'a','earnings'),250);assert.equal(subscribe(db,'b','CUSTOM',2500,'deposit',start,'custom-request-001').id,c.id);assert.equal(balance(db,'a','earnings'),250)})
test('cofre cadastrado mantém resgate na origem após edição da modalidade',()=>{const db=fixture();savePlan(db,'admin',{...plan,family:'vault',days:0});const c=subscribe(db,'a','CUSTOM',2500,'deposit',start);savePlan(db,'admin',{family:'daily',days:20},'CUSTOM');accrue(db,new Date(+start+DAY));redeem(db,'a',c.id,new Date(+start+DAY));assert.equal(balance(db,'a','vault'),0);assert.equal(balance(db,'a','deposit'),100000);assert.equal(balance(db,'a','earnings'),25)})
