import 'dotenv/config'
import express,{type Request,type Response,type NextFunction} from 'express'
import crypto from 'node:crypto'
import path from 'node:path'
import fs from 'node:fs'
import {createStore} from './store.js'
import {deleteParticipant,updateParticipant,resetParticipantPassword} from './accounts.js'
import {approveDeposit,addParticipantBalance} from './admin-payments.js'
import {confirmDeposit,attachPayment,reviewStaleDeposits} from './payments.js'
import {emptyDb,id,entry,balance,canWithdraw,subscribe,accrue,redeem,withdraw,settleWithdrawal,network,salary,draw,userSpins,audit,type Db,type Account} from './engine.js'
import {amount,PLANS,validatePlanLimits,type Rules} from '../src/rules.js'
import {createPixPayTransaction,normalizeCustomerDocument,verifyPixPayWebhookToken,pixPayConfig} from './pixpay.js'

import {hash,verify} from './passwords.js'
import {validPassword} from '../src/security.js'
import {validateSupport} from '../src/support.js'
import {installPhoneAuth} from './phone-auth.js'
import {customerEmail,completePaymentProfile} from './customer-profile.js'

const safe=(user:Account)=>{const {passwordHash,...rest}=user;return rest}
const tokenHash=(token:string)=>crypto.createHash('sha256').update(token).digest('hex')
function generateInviteCode(db:Db){let code:string;do{code=crypto.randomBytes(8).toString('hex')}while(!/[a-z]/.test(code)||!/[0-9]/.test(code)||db.users.some(u=>u.inviteCode===code));return code}
function seed(){const db=emptyDb(),password=process.env.CREDNEX_ADMIN_PASSWORD||'';if(password.length<12)throw new Error('Configure CREDNEX_ADMIN_PASSWORD com pelo menos 12 caracteres');db.users.push({id:id(),name:'Administrador CREDNEX',username:process.env.CREDNEX_ADMIN_USERNAME||'admin',email:process.env.CREDNEX_ADMIN_EMAIL||'admin@crednex.local',passwordHash:hash(password),role:'ADMIN_MASTER',status:'ACTIVE',sponsorId:null,inviteCode:'crednex'});return db}
const store=createStore(seed)
export const app=express()
// Production Nginx is the only trusted proxy; direct clients cannot override their IP.
app.set('trust proxy','loopback')
app.disable('x-powered-by');app.use(express.json({limit:'64kb'}))
app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Cache-Control','no-store');next()})
const attempts=new Map<string,{count:number;until:number}>()
app.use('/api/auth',(req,res,next)=>{const key=req.ip||'unknown',now=Date.now();if(attempts.size>10000)for(const [k,v] of attempts)if(v.until<now)attempts.delete(k);let value=attempts.get(key);if(!value||value.until<now){value={count:0,until:now+900000};attempts.set(key,value)}if(++value.count>30)return res.status(429).json({error:'Muitas tentativas. Aguarde 15 minutos.'});next()})
function account(db:Db,req:Request,admin=false){const session=db.sessions[tokenHash((req.headers.authorization||'').replace(/^Bearer /,''))],user=db.users.find(u=>u.id===session?.userId);if(!session||session.expires<Date.now()||!user||user.status!=='ACTIVE')throw Object.assign(new Error('Sessão expirada'),{status:401});if(admin&&user.role!=='ADMIN_MASTER')throw Object.assign(new Error('Acesso restrito'),{status:403});return user}
const route=(method:'get'|'post'|'patch'|'delete',url:string|string[],fn:(db:Db,req:Request)=>unknown|Promise<unknown>)=>app[method](url,async(req,res,next)=>{try{const result=await store.transaction(db=>fn(db,req));res.json(result)}catch(e){next(e)}})
route('get','/api/public',db=>({plans:PLANS,rules:db.rules,brand:'CredNEX'}))
installPhoneAuth(app,store,safe,generateInviteCode)
route('post','/api/auth/register',(db,req)=>{const {name,username,email,password,inviteCode}=req.body||{};if(typeof name!=='string'||name.trim().length<2||typeof username!=='string'||!/^[a-z0-9._-]{3,40}$/i.test(username)||typeof email!=='string'||!/^\S+@\S+\.\S+$/.test(email)||!validPassword(password))throw new Error('Informe nome, usuário, e-mail e senha com pelo menos 8 caracteres');if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()||u.email.toLowerCase()===email.toLowerCase()))throw new Error('Usuário ou e-mail já cadastrado');const code=inviteCode===undefined||inviteCode===''?'crednex':inviteCode;if(typeof code!=='string'||!/^[a-z0-9]+$/i.test(code))throw new Error('Código de indicação deve conter apenas letras e números');const sponsor=db.users.find(u=>u.inviteCode===code&&u.status==='ACTIVE');if(!sponsor)throw new Error('Convite inválido');const user:Account={id:id(),name:name.trim(),username:username.toLowerCase(),email:email.toLowerCase(),passwordHash:hash(password),role:'ASSOCIATE',status:'ACTIVE',sponsorId:sponsor.id,inviteCode:generateInviteCode(db)};db.users.push(user);audit(db,user.id,'REGISTER',{});return {ok:true}})
route('post','/api/auth/login',(db,req)=>{const user=db.users.find(u=>u.username===String(req.body.username||'').toLowerCase());if(!user||user.status!=='ACTIVE'||typeof req.body.password!=='string'||!verify(req.body.password,user.passwordHash))throw Object.assign(new Error('Usuário ou senha incorretos'),{status:401});const token=crypto.randomBytes(32).toString('hex');for(const [key,s] of Object.entries(db.sessions))if(s.expires<Date.now())delete db.sessions[key];db.sessions[tokenHash(token)]={userId:user.id,expires:Date.now()+12*3600000};return {token,user:safe(user)}})
route('post','/api/auth/logout',(db,req)=>{delete db.sessions[tokenHash((req.headers.authorization||'').replace(/^Bearer /,''))];return {ok:true}})
route('get','/api/state',(db,req)=>{const user=account(db,req);accrue(db);reviewStaleDeposits(db);const own=(rows:any[])=>rows.filter(r=>r.userId===user.id);return {hasActivePackage:canWithdraw(db,user.id),user:safe(user),rules:db.rules,support:db.support,balances:{deposit:balance(db,user.id,'deposit'),earnings:balance(db,user.id,'earnings'),vault:balance(db,user.id,'vault')},contracts:own(db.contracts),ledger:own(db.ledger).slice().reverse(),deposits:own(db.deposits),withdrawals:own(db.withdrawals),tickets:own(db.tickets),spins:userSpins(db,user.id),network:network(db,user.id).map(n=>({id:n.user.id,name:n.user.name,level:n.level,active:n.active}))}})
route('post','/api/contracts',(db,req)=>{const user=account(db,req);accrue(db);const c=subscribe(db,user.id,String(req.body.planId),amount(req.body.amount),req.body.wallet,new Date(),req.body.requestId);audit(db,user.id,'SUBSCRIBE',{contractId:c.id});return c})
route('post','/api/vault/redeem',(db,req)=>{const user=account(db,req);redeem(db,user.id,String(req.body.contractId));return {ok:true}})
route('post','/api/withdrawals',(db,req)=>{const user=account(db,req);accrue(db);const w=withdraw(db,user.id,req.body.wallet,amount(req.body.amount),String(req.body.pixKey||''));audit(db,user.id,'WITHDRAWAL_REQUEST',{id:w.id});return w})
route('post','/api/spins/draw',(db,req)=>draw(db,account(db,req).id))
route('patch','/api/profile',(db,req)=>{const user=account(db,req);if(user.phone&&req.body.email!==undefined)user.email=customerEmail(db,user,req.body.email);if(typeof req.body.name==='string'&&req.body.name.trim().length>=2)user.name=req.body.name.trim().slice(0,100);if(typeof req.body.pixKey==='string')user.pixKey=req.body.pixKey.trim().slice(0,150);if(req.body.newPassword){if(!verify(String(req.body.currentPassword||''),user.passwordHash)||!validPassword(req.body.newPassword))throw new Error('Confira a senha atual e use uma nova senha de 8 a 128 caracteres');user.passwordHash=hash(req.body.newPassword);for(const [k,s]of Object.entries(db.sessions))if(s.userId===user.id)delete db.sessions[k]}audit(db,user.id,'PROFILE_UPDATE',{});return safe(user)})
route('post','/api/tickets',(db,req)=>{const user=account(db,req),subject=String(req.body.subject||'').trim(),message=String(req.body.message||'').trim();if(!subject||subject.length>200||!message||message.length>5000)throw new Error('Informe assunto (até 200 caracteres) e mensagem de até 5000 caracteres');const ticket={id:id(),userId:user.id,subject,status:'OPEN',at:new Date().toISOString(),messages:[{author:user.name,text:message,at:new Date().toISOString()}]};db.tickets.push(ticket);return ticket})
route('post','/api/tickets/:id/reply',(db,req)=>{const user=account(db,req),ticket=db.tickets.find(t=>t.id===req.params.id&&(t.userId===user.id||user.role==='ADMIN_MASTER'));if(!ticket)throw new Error('Ticket não encontrado');const text=String(req.body.message||'').trim();if(!text||text.length>5000)throw new Error('Mensagem inválida');ticket.messages.push({author:user.name,text,at:new Date().toISOString()});ticket.status=req.body.close&&user.role==='ADMIN_MASTER'?'CLOSED':'OPEN';return ticket})
// Persist intent before calling the gateway. A provider timeout never credits a wallet.
app.post('/api/deposits',async(req,res,next)=>{let depositId='';try{const intent=await store.transaction(db=>{const user=account(db,req),cents=amount(req.body.amount),document=normalizeCustomerDocument(req.body.document);if(cents<db.rules.depositMin)throw new Error('Depósito mínimo de R$40,00');completePaymentProfile(db,user,req.body);pixPayConfig();const item={id:id(),userId:user.id,cents,status:'CREATING',at:new Date().toISOString()};db.deposits.push(item);depositId=item.id;return {item,name:user.name,email:user.email,document}});const payment=await createPixPayTransaction({amount:intent.item.cents/100,customerName:intent.name,customerEmail:intent.email,customerDocument:intent.document,depositId:intent.item.id});const result=await store.transaction(db=>{return attachPayment(db,depositId,payment)});res.json(result)}catch(e){if(depositId)await store.transaction(db=>{const d=db.deposits.find(d=>d.id===depositId);if(d&&d.status==='CREATING')d.status='REVIEW_REQUIRED'});next(e)}})
route('post',['/api/webhooks/2pp','/api/webhooks/pixpay'],(db,req)=>{if(!verifyPixPayWebhookToken(req.query.token))throw Object.assign(new Error('Webhook inválido'),{status:401});return confirmDeposit(db,req.body,typeof req.query.depositId==='string'?req.query.depositId:undefined)})
route('get','/api/admin/state',(db,req)=>{account(db,req,true);accrue(db);reviewStaleDeposits(db);return {...db,users:db.users.map(safe),sessions:undefined}})
route('post','/api/admin/deposits/:id/approve',(db,req)=>approveDeposit(db,account(db,req,true).id,String(req.params.id),req.body.reference))
route('post','/api/admin/users/:id/balance',(db,req)=>addParticipantBalance(db,account(db,req,true).id,String(req.params.id),req.body))
route('delete','/api/admin/users/:id',(db,req)=>deleteParticipant(db,account(db,req,true).id,String(req.params.id)))
route('patch','/api/admin/users/:id',(db,req)=>updateParticipant(db,account(db,req,true).id,String(req.params.id),req.body))
route('post','/api/admin/users/:id/password',(db,req)=>resetParticipantPassword(db,account(db,req,true).id,String(req.params.id),req.body.password,req.body.confirmPassword))
route('patch','/api/admin/support',(db,req)=>{const admin=account(db,req,true);db.support=validateSupport(req.body);audit(db,admin.id,'SUPPORT_UPDATED',{});return db.support})
route('post','/api/admin/withdrawals/:id',(db,req)=>{const admin=account(db,req,true);settleWithdrawal(db,String(req.params.id),String(req.body.status),String(req.body.reference||''));audit(db,admin.id,'WITHDRAWAL_SETTLED',{id:req.params.id,status:req.body.status});return {ok:true}})
route('post','/api/admin/process',(db,req)=>{const admin=account(db,req,true);const count=accrue(db);salary(db);audit(db,admin.id,'PROCESS_EARNINGS',{count});return {count}})
route('patch','/api/admin/rules',(db,req)=>{const admin=account(db,req,true),r=req.body as Rules;if(db.rules.confirmed&&!r.confirmed&&req.body.pauseConfirmation!=='PAUSAR COMPRAS')throw new Error('Para desativar contratações, confirme digitando PAUSAR COMPRAS. Salvar outras regras não deve bloquear os participantes');if(typeof r.confirmed!=='boolean'||typeof r.returnPrincipal!=='boolean'||r.depositMin!==4000||!['deposit','earnings'].includes(r.commissionBase)||!['direct','network'].includes(r.salaryScope)||!Array.isArray(r.prizes)||r.prizes.length>20)throw new Error('Configuração inválida');if(r.prizes.some(p=>typeof p.label!=='string'||!p.label.trim()||!Number.isSafeInteger(p.cents)||p.cents<0||p.cents>1000000||!Number.isInteger(p.weight)||p.weight<1)||r.prizes.reduce((s,p)=>s+p.weight,0)>1000000)throw new Error('Prêmios ou pesos inválidos');db.rules={activePlanLimits:validatePlanLimits(r.activePlanLimits ?? db.rules.activePlanLimits),confirmed:r.confirmed,depositMin:4000,returnPrincipal:r.returnPrincipal,commissionBase:r.commissionBase,salaryScope:r.salaryScope,prizes:r.prizes.map(p=>({label:p.label.slice(0,80),cents:p.cents,weight:p.weight}))};audit(db,admin.id,'RULES_UPDATED',db.rules);return db.rules})
route('get','/api/cron/accrue',(db,req)=>{const secret=process.env.CRON_SECRET;if(!secret||secret.length<24||req.headers.authorization!==`Bearer ${secret}`)throw Object.assign(new Error('Acesso negado'),{status:401});const count=accrue(db);salary(db);return {count}})
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'CREDNEX'}))
app.use('/api',(_req,res)=>res.status(404).json({error:'Rota não encontrada'}))
app.use((error:any,_req:Request,res:Response,_next:NextFunction)=>{res.status(error.status||422).json({error:error.message||'Falha na operação'})})
const dist=path.resolve('dist');if(fs.existsSync(dist)){app.use(express.static(dist));app.get(/.*/,(_req,res)=>res.sendFile(path.join(dist,'index.html')))}
if(process.env.CREDNEX_NO_LISTEN!=='1'&&!process.env.VERCEL){const port=Number(process.env.PORT||4020);app.listen(port,'127.0.0.1',()=>console.log(`CREDNEX: http://localhost:${port}`));setInterval(()=>void store.transaction(db=>{accrue(db);salary(db)}).catch(e=>console.error('Processamento:',e.message)),60000).unref()}
