import {useState,type FormEvent} from 'react'
import {type Plan,returnsPrincipal} from './catalog'
type Row=Record<string,any>
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100)
export function ParticipantContracts({userId,data,submit}:{userId:string;data:Row;submit:(id:string|undefined,body:Row)=>Promise<unknown>}){
 const [editing,setEditing]=useState<Row|null|undefined>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestId,setRequestId]=useState('')
 const plans:Plan[]=data.plans,contracts:Row[]=data.contracts.filter((c:Row)=>c.userId===userId)
 const begin=(c:Row|null)=>{setEditing(c?{...c,revision:data.audit.filter((a:Row)=>a.action==='ADMIN_CONTRACT_UPDATED'&&a.details.contractId===c.id).length}:null);setError('');setRequestId(crypto.randomUUID())}
 const send=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const v=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{const body=editing?{...v,days:Number(v.days),returnPrincipal:v.returnPrincipal==='on',refund:v.refund==='on',revision:editing.revision}:{...v,requestId};await submit(editing?.id,body);setEditing(undefined)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section><div className="section-heading"><div><h3>Planos do participante</h3><p>Inclua, ajuste ou encerre aplicações. Todas as ações exigem motivo e ficam na auditoria.</p></div><button className="primary" disabled={busy} onClick={()=>begin(null)}>Incluir plano</button></div>
 {editing!==undefined&&<div className="panel"><h3>{editing?'Editar aplicação':'Incluir plano para o participante'}</h3>{error&&<div className="alert error" role="alert">{error}</div>}<form key={editing?.id??requestId} onSubmit={send}><div className="participant-form-grid"><label>Plano<select name="planId" defaultValue={editing?.planId} required>{plans.filter(p=>editing||p.active).map(p=><option key={p.id} value={p.id}>{p.name}{p.active?'':' (inativo)'}</option>)}</select></label><label>Capital aplicado (R$)<input name="amount" type="number" step="0.01" min="0.01" max="1000000" required defaultValue={editing?editing.principal/100:undefined}/></label>
 {!editing?<label>Origem do capital<select name="source"><option value="deposit">Debitar Carteira de Saldo</option><option value="earnings">Debitar Carteira de Rendimentos</option><option value="grant">Concessão administrativa (sem debitar saldo existente)</option></select></label>:<><label>Taxa diária (%)<input name="rate" type="number" min="0.01" max="100" step="0.01" required defaultValue={editing.bps/100}/></label><label>Prazo total em dias (cofre: zero)<input name="days" type="number" min="0" max="3650" required defaultValue={editing.days}/></label><label>Ação<select name="action"><option value="edit">Salvar condições para os próximos rendimentos</option><option value="close">Encerrar aplicação agora</option></select></label></>}
 <label>Motivo administrativo<input name="reason" required minLength={3} maxLength={500}/></label></div>
 {editing?<><label className="check"><input name="returnPrincipal" type="checkbox" defaultChecked={editing.returnPrincipal}/>Devolver capital ao terminar o prazo</label><label className="check"><input name="refund" type="checkbox" defaultChecked/>Se encerrar agora, devolver capital às carteiras de origem</label><p>Já pagos: {editing.paidDays} dias. O início e os pagamentos anteriores serão mantidos. A mudança de plano não copia sua taxa ou prazo: confira os campos acima. Aumento de capital debita a carteira de origem; redução devolve o valor. A edição não refaz comissões anteriores.</p></>:<p>A inclusão segue taxas, prazo, limites e comissões do plano e das regras atuais. A concessão cria um crédito administrativo aplicado imediatamente; esse capital não poderá ser sacado.</p>}
 <div className="inline-actions"><button className="primary" disabled={busy}>{busy?'Salvando…':'Confirmar alteração'}</button><button type="button" className="outline" disabled={busy} onClick={()=>setEditing(undefined)}>Cancelar</button></div></form></div>}
 <div className="participant-grid">{contracts.map(c=><article className="panel" key={c.id}><h3>{c.planName||c.planId}</h3><p>{c.status==='ACTIVE'?'Ativo':'Encerrado'} · {money(c.principal)}</p><p>{c.bps/100}% ao dia · {c.days?`${c.paidDays}/${c.days} dias pagos`:`${c.paidDays} dias pagos, prazo flexível`}</p><p>Capital: {c.returnPrincipal?'devolvido ao final':'sem devolução adicional'}</p><small>Início: {new Date(c.startedAt).toLocaleString('pt-BR')}</small><button className="outline" disabled={busy||c.status!=='ACTIVE'} onClick={()=>begin(c)}>Editar / encerrar plano</button></article>)}</div>{!contracts.length&&<p>Nenhuma aplicação cadastrada para este participante.</p>}
 <details className="panel"><summary>Condições dos planos disponíveis</summary>{plans.filter(p=>p.active).map(p=><p key={p.id}>{p.name}: {money(p.min)} a {money(p.max)}, {p.bps/100}% ao dia, {p.days?`${p.days} dias`:'prazo flexível'}, capital {returnsPrincipal(p,data.rules)?'devolvido':'sem devolução adicional'}.</p>)}</details>
 </section>
}
