import {useState,type FormEvent,type ReactNode} from 'react'
import {ArrowLeft,ArrowRight,Search,UserRound,Wallet,LockKeyhole} from 'lucide-react'
import {MIN_PASSWORD_LENGTH} from './security'
type Row=Record<string,any>
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100)
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value))

export function Participants({data,save,resetPassword,open,contractsTable,ledgerTable}:{data:Row;save:(id:string,values:Row)=>Promise<unknown>;resetPassword:(id:string,values:Row)=>Promise<unknown>;open:(kind:string,id:string)=>void;contractsTable:(rows:Row[])=>ReactNode;ledgerTable:(rows:Row[])=>ReactNode}){
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('ALL'),[selected,setSelected]=useState(''),[tab,setTab]=useState('profile')
  const users:Row[]=data.users.filter((u:Row)=>u.role==='ASSOCIATE'),user=users.find(u=>u.id===selected)
  const own=(rows:Row[])=>rows.filter(row=>row.userId===selected)
  const balances=(userId:string,wallet:string)=>data.ledger.filter((e:Row)=>e.userId===userId&&e.wallet===wallet).reduce((sum:number,e:Row)=>sum+e.cents,0)
  if(user)return <section className="participant-detail"><button className="text-btn" onClick={()=>setSelected('')}><ArrowLeft size={16}/>Voltar aos participantes</button><div className="section-heading participant-heading"><div><span className="eyebrow">CADASTRO DO PARTICIPANTE</span><h2>{user.name}</h2><p>{user.phone||`@${user.username}`} · {user.email||'E-mail não informado'}</p></div><span className={`badge ${user.status.toLowerCase()}`}>{user.status==='ACTIVE'?'Ativo':'Bloqueado'}</span></div><div className="stats-grid three">{[['deposit','Saldo para aplicar'],['earnings','Rendimentos'],['vault','Credcofre']].map(([wallet,label])=><div className="stat" key={wallet}><span>{label}</span><strong>{money(balances(user.id,wallet))}</strong></div>)}</div><div className="participant-actions"><button className="primary" disabled={user.status!=='ACTIVE'} onClick={()=>open('addBalance',user.id)}><Wallet size={17}/>Adicionar saldo</button></div><nav className="detail-tabs" aria-label="Dados do participante">{[['profile','Cadastro'],['security','Senha e acesso'],['finance','Histórico financeiro']].map(([value,label])=><button key={value} className={tab===value?'active':''} aria-pressed={tab===value} onClick={()=>setTab(value)}>{label}</button>)}</nav>
    {tab==='profile'&&<div className="panel"><h3>Dados cadastrais</h3><p>Edite os dados usados no acesso e no atendimento deste participante.</p><ParticipantForm key={user.id+user.username+user.email+user.name+(user.pixKey||'')+(user.phone||'')} user={user} submit={values=>save(user.id,values)}/><dl className="participant-meta"><dt>Código de indicação</dt><dd>{user.inviteCode}</dd><dt>Patrocinador</dt><dd>{data.users.find((u:Row)=>u.id===user.sponsorId)?.name||'Sem patrocinador'}</dd><dt>Identificador da conta</dt><dd>{user.id}</dd></dl></div>}
    {tab==='security'&&<div className="profile-grid"><div className="panel"><LockKeyhole size={24}/><h3>Redefinir senha</h3><p>Cadastre uma nova senha para o participante. Os acessos atuais serão encerrados e ele deverá entrar novamente.</p><PasswordReset key={user.id} submit={values=>resetPassword(user.id,values)}/></div><div className="panel"><h3>Situação da conta</h3><p>{user.status==='ACTIVE'?'O participante pode acessar sua conta. Bloquear encerra suas sessões e impede novos acessos.':'A conta está bloqueada. Reative para permitir novos acessos.'}</p><StatusButton user={user} save={save}/><div className="account-danger"><h3>Excluir participante</h3><p>A exclusão é permanente. Saldos e pendências precisam estar resolvidos.</p><button className="outline danger" onClick={()=>open('deleteUser',user.id)}>Excluir conta</button></div></div></div>}
    {tab==='finance'&&<><div className="panel"><h3>Aplicações</h3>{contractsTable(own(data.contracts))}</div><div className="panel"><h3>Extrato completo</h3>{ledgerTable(own(data.ledger).slice().reverse())}</div><div className="panel"><h3>Depósitos e saques</h3>{[...own(data.deposits).map((r):Row=>({...r,kind:'Depósito PIX'})),...own(data.withdrawals).map((r):Row=>({...r,kind:'Saque'}))].sort((a,b)=>b.at.localeCompare(a.at)).map(r=><div className="participant-movement" key={r.id}><div><strong>{r.kind}</strong><small>{date(r.at)}</small></div><strong>{money(r.cents)}</strong><span>{({PAID:'Pago',PENDING:'Pendente',REJECTED:'Recusado',REVIEW_REQUIRED:'Requer conferência',CREATING:'Gerando cobrança'} as Row)[r.status]||r.status}</span></div>)}{!own(data.deposits).length&&!own(data.withdrawals).length&&<p>Nenhum depósito ou saque registrado.</p>}</div></>}
  </section>
  const visible=users.filter(u=>(filter==='ALL'||u.status===filter)&&`${u.name} ${u.username} ${u.email} ${u.phone||''} ${u.id}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))
  return <section><div className="section-heading"><div><h2>Gerenciar participantes</h2><p>Consulte o cadastro, acompanhe saldos e gerencie o acesso de cada cliente.</p></div><span className="pill">{users.length} participantes</span></div><div className="participant-filters"><label><span><Search size={15}/>Buscar participante</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, telefone, usuário ou e-mail"/></label><label>Situação<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Todas as contas</option><option value="ACTIVE">Ativas</option><option value="BLOCKED">Bloqueadas</option></select></label></div><div className="participant-grid">{visible.map(u=><article className="panel participant-card" key={u.id}><div className="participant-card-heading"><span className="participant-icon"><UserRound size={23}/></span><div><h3>{u.name}</h3><small>{u.phone||`@${u.username}`}</small></div><span className={`badge ${u.status.toLowerCase()}`}>{u.status==='ACTIVE'?'Ativo':'Bloqueado'}</span></div><p>{u.email||'E-mail não informado'}</p><div className="participant-card-balance"><span>Saldo total</span><strong>{money(['deposit','earnings','vault'].reduce((sum,w)=>sum+balances(u.id,w),0))}</strong></div><button className="outline" onClick={()=>{setSelected(u.id);setTab('profile')}}>Ver cadastro e gerenciar<ArrowRight size={16}/></button></article>)}</div>{!visible.length&&<div className="panel"><p>Nenhum participante encontrado.</p></div>}</section>
}
function ParticipantForm({user,submit}:{user:Row;submit:(values:Row)=>Promise<unknown>}){
  const [busy,setBusy]=useState(false)
  return <form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await submit(values)}finally{setBusy(false)}}}><div className="participant-form-grid"><label>Nome completo<input name="name" defaultValue={user.name} required minLength={2} maxLength={100}/></label><label>Usuário de acesso<input name="username" defaultValue={user.username} required minLength={3} maxLength={40} pattern="[A-Za-z0-9._\-]+"/></label><label>E-mail<input name="email" type="email" defaultValue={user.email} required={!user.phone} maxLength={254}/></label><label>Telefone de acesso<input name="phone" type="tel" defaultValue={user.phone||''} required={!!user.phone} maxLength={25}/></label><label>Chave PIX<input name="pixKey" defaultValue={user.pixKey||''} maxLength={150}/></label></div><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar dados cadastrais'}</button></form>
}
function PasswordReset({submit}:{submit:(values:Row)=>Promise<unknown>}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('')
  return <form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const form=e.currentTarget,values=Object.fromEntries(new FormData(form));setError('');if(values.password!==values.confirmPassword){setError('As senhas não conferem');return}setBusy(true);try{if(await submit(values))form.reset()}finally{setBusy(false)}}}>{error&&<p role="alert">{error}</p>}<label>Nova senha<input name="password" type="password" required minLength={MIN_PASSWORD_LENGTH} maxLength={128} autoComplete="new-password"/><small>Mínimo de {MIN_PASSWORD_LENGTH} caracteres.</small></label><label>Confirmar nova senha<input name="confirmPassword" type="password" required minLength={MIN_PASSWORD_LENGTH} maxLength={128} autoComplete="new-password"/></label><button className="primary" disabled={busy}>{busy?'Redefinindo…':'Redefinir senha'}</button></form>
}
function StatusButton({user,save}:{user:Row;save:(id:string,values:Row)=>Promise<unknown>}){
  const [busy,setBusy]=useState(false)
  return <button className="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await save(user.id,{status:user.status==='ACTIVE'?'BLOCKED':'ACTIVE'})}finally{setBusy(false)}}}>{busy?'Atualizando…':user.status==='ACTIVE'?'Bloquear acesso':'Reativar acesso'}</button>
}
