import {useState,type FormEvent} from 'react'
import {Headphones,ArrowUpRight,Clock} from 'lucide-react'
import {validateSupport,type SupportSettings} from './support'
export function SupportPanel({settings,admin,save}:{settings:SupportSettings;admin:boolean;save:(values:SupportSettings)=>Promise<unknown>}){
  return <><div className="support-grid"><section className="panel support-contact"><Headphones size={30}/><span className="eyebrow">FALE COM A CREDNEX</span><h2>Suporte no WhatsApp</h2><p>Acesse nosso grupo para receber orientações da equipe de atendimento.</p>{settings.whatsappGroupUrl?<a className="primary" href={settings.whatsappGroupUrl} target="_blank" rel="noopener noreferrer">Abrir grupo de suporte<ArrowUpRight size={17}/></a>:<p>{admin?'Configure abaixo o link do grupo para liberar o acesso pelo WhatsApp.':'O acesso ao grupo será disponibilizado em breve. Você pode abrir um chamado abaixo.'}</p>}</section><section className="panel support-hours"><Clock size={26}/><h3>Horários de atendimento</h3><dl><div><dt>Segunda a sexta</dt><dd>12h às 18h</dd></div><div><dt>Sábado e domingo</dt><dd>12h às 15h</dd></div></dl><small>Horário de Brasília</small></section></div>{admin&&<SupportSettingsForm key={settings.whatsappGroupUrl} settings={settings} save={save}/>}</>
}
function SupportSettingsForm({settings,save}:{settings:SupportSettings;save:(values:SupportSettings)=>Promise<unknown>}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false)
  return <section className="panel"><h3>Configurar grupo de suporte</h3><form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;setError('');const values=new FormData(e.currentTarget);setBusy(true);try{await save(validateSupport({whatsappGroupUrl:values.get('whatsappGroupUrl')}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Link de convite do grupo no WhatsApp<input name="whatsappGroupUrl" type="url" defaultValue={settings.whatsappGroupUrl} placeholder="https://chat.whatsapp.com/…"/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar grupo de suporte'}</button></form></section>
}
